### ISSUE TITLE
Multiple clap bug 

### ISSUE THREAD

**Issue by astocker-scottlogic** [ScottLogic/blog#139]
If you click multiple times in quick succession on the clap button, you can register more than one clap. After you refresh the page it will also jump up to some arbitrary number.

**Comment by ColinEberhardt** [comment]
Having the ability to provide multiple claps (up to 10) is a feature:

https://applause-button.com/

However, the server-side counter applies various other checks (avoiding multiple claps from the same IP, throttling), which can mean that the server and client are out of synchronisation.

I'm sure it can be improved though.

**Comment by chriswilty** [comment]
Some of the not-quite-multiclap problems have been ironed out in the latest release of applause-button, so clicking twice in quick succession should now send the correct number of claps to the server, and the UI should also remain in sync. Note that the limitations @ColinEberhardt mentions still apply, in that the server can return a lower number than the UI shows when the claps are registered, but then the UI immediately updates on response to show the actual registered claps.

Therefore I think this one will be resolved in #250
