### ISSUE TITLE
Clap button is a little high up

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/blog#148]
When the branding changed, the top banner became a bit taller. As a result, the clap button now sits slightly under the banner:

![image](https://github.com/ScottLogic/blog/assets/1098110/2dcf7145-721a-4ac5-9b49-4f6c049ffb3e)

**Comment by chriswilty** [comment]
My observations:
- blog header is 89px height, which is 40px (=2.5rem) for the h1 plus top margin (1.6875rem) plus bottom margin (1.375rem)
- clap count is 40% of the applause icon height (60px) which is 24px (=1.5rem)

These sum to 113px (=7.0625rem) which is what we'd want offset from top to be (for the `<applause-button>` element).

Alternatively, we take all these calculations out of the picture, and put the count _under_ the clap icon:

![image](https://github.com/ScottLogic/blog/assets/15246391/3bf9274f-9db7-4f85-869d-ad08e9a43cd4)
