### ISSUE TITLE
Use tags as page keywords

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/blog#254]
Pretty much every post has some **tags** defined: this is a built-in variable for [post front matter](https://jekyllrb.com/docs/front-matter/#predefined-variables-for-posts). However, it looks like these are not really being used: not in the rendered page, not in code logic for finding related posts. The only tag that is used is "featured", to make selected posts sticky (on author and category pages).

How about we add tags as _keywords_ to each post? That should help with SEO.

In `_layouts/default.html` we would add a new meta tag to hold the keywords, something like this:

```html
  {% unless page.tags == empty %}
  <meta name="keywords" content="{{page.tags | join: ' '}}" />
  {% endif %}
```

**Comment by ColinEberhardt** [comment]
I think this is worth mocking up to see how it might look - definitely worth considering.
