### ISSUE TITLE
Posts not showing in categories

### ISSUE THREAD

**Issue by godds** [ScottLogic/blog#27]
e.g. https://blog.scottlogic.com/2022/06/16/pride-2022.html and https://blog.scottlogic.com/2022/01/05/new-normal-for-leadership.html not showing under People.

**Comment by godds** [comment]
and https://blog.scottlogic.com/2014/02/04/intro-to-ixd.html not showing in UX Design

**Comment by Jahoe** [comment]
There seemed to have been a discrepancy in the category name in some of these. Some started with a lowercase `p` in `People`. Fixed in PR #30
