### ISSUE TITLE
Post(s) not included

### ISSUE THREAD

**Issue by godds** [ScottLogic/blog#29]
e.g. https://github.com/ScottLogic/blog/blob/gh-pages/_posts/2014-07-31-hiphop.md

Appears to be the case since this commit: https://github.com/ScottLogic/blog/commit/5d9d76aa8f4e1458bda249ba5d77ac81e7f4e300

**Comment by Jahoe** [comment]
One post (HipHop) had been set to hidden, which has been removed. Another had a malformed name which has been also fixed with MR #30
