### ISSUE TITLE
Update footer to match www

### ISSUE THREAD

**Issue by godds** [ScottLogic/blog#93]
The www.scottlogic.com footer has recently been updated, highlighting that the blog footer is quite a way out of sync with it.

www:
![Screenshot 2023-11-01 at 10 13 28](https://github.com/ScottLogic/blog/assets/2734551/360e5080-ca49-49df-8207-4db9bc6a50bc)

blog:
![Screenshot 2023-11-01 at 10 13 21](https://github.com/ScottLogic/blog/assets/2734551/2b4c19cb-2096-4a1d-9eef-bb2bc81c483b)

Need to update the layout and content of the blog footer to match www.scottlogic.com

**Comment by Obikaviola** [comment]
Can I be assigned this?

**Comment by toan300902** [comment]
Hello, Can I be assigned this?
